# Generated by Django 3.1 on 2021-09-02 20:08

from django.db import migrations, models
import garpix_notify.mixins.user_notify_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0002_auto_20210628_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='telegram_secret',
            field=models.CharField(default=garpix_notify.mixins.user_notify_mixin.generate_uuid, max_length=150, unique=True, verbose_name='Ключ подключения Telegram'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_bad_command_text',
            field=models.TextField(blank=True, default='Неправильный формат команды', verbose_name='Telegram - Текст неправильной команды бота'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_bot_name',
            field=models.CharField(blank=True, default='', help_text='Например, MySuperBot', max_length=255, verbose_name='Telegram Имя бота'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_failed_added_text',
            field=models.TextField(blank=True, default='Ошибка при привязке учетной записи. Пожалуйста, свяжитесь с техподдержкой', verbose_name='Telegram - Текст провал, не добавлен код'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_help_text',
            field=models.TextField(blank=True, default='Используйте команду /set <уникальный код> для того, чтобы получать сообщения от бота. Уникальный код вы можете получить на нашем сайте', verbose_name='Telegram - Текст помощи бота'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_success_added_text',
            field=models.TextField(blank=True, default='Ваша учетная запись успешно привязана к боту. Вы будете получать уведомления!', verbose_name='Telegram - Текст успешно добавлен код'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='telegram_welcome_text',
            field=models.TextField(blank=True, default='Добрый день! Здесь вы можете получать уведомления от нашего сайта', verbose_name='Telegram - Приветственный текст бота'),
        ),
        migrations.AddField(
            model_name='notifytemplate',
            name='telegram_secret',
            field=models.CharField(default=garpix_notify.mixins.user_notify_mixin.generate_uuid, max_length=150, unique=True, verbose_name='Ключ подключения Telegram'),
        ),
        migrations.AddField(
            model_name='notifyuserlistparticipant',
            name='telegram_secret',
            field=models.CharField(default=garpix_notify.mixins.user_notify_mixin.generate_uuid, max_length=150, unique=True, verbose_name='Ключ подключения Telegram'),
        ),
    ]
