# Generated by Django 3.1 on 2022-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0003_auto_20210902_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber'), (5, 'System')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber'), (5, 'System')], verbose_name='Тип'),
        ),
    ]
