# Generated by Django 3.1 on 2022-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0005_notify_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyconfig',
            name='sms_url',
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='sms_login',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Логин пользователя СМС провайдера'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='sms_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль для api СМС провайдера'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='sms_url_type',
            field=models.IntegerField(choices=[(0, 'sms.ru'), (1, 'web.szk-info.ru')], default=0, verbose_name='URL СМС провайдера'),
        ),
    ]
