# Generated by Django 3.1 on 2022-06-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0007_auto_20220519_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifyerrorlog',
            options={'verbose_name': 'Лог отправки уведомления', 'verbose_name_plural': 'Логи отправки уведомления'},
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='call_api_id',
            field=models.CharField(blank=True, default='1234567890', max_length=255, verbose_name='API ID оператора связи'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='call_login',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Логин пользователя оператора связи'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='call_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль для api СМС провайдера'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='call_url_type',
            field=models.IntegerField(choices=[(0, 'sms.ru API'), (1, 'sms.ru LOGIN')], default=0, verbose_name='URL звонка провайдера'),
        ),
        migrations.AddField(
            model_name='notifyconfig',
            name='is_call_enabled',
            field=models.BooleanField(default=True, verbose_name='Разрешить отправку звонков'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber'), (5, 'System'), (6, 'Call')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber'), (5, 'System'), (6, 'Call')], verbose_name='Тип'),
        ),
    ]
