# Generated by Django 3.2 on 2022-08-22 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import garpix_notify.mixins.notify_method_mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_notify', '0010_auto_20220713_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'E-mail'), (1, 'SMS'), (2, 'Push'), (3, 'Telegram'), (4, 'Viber'), (5, 'System'), (6, 'Call'), (7, 'WhatsApp')], default=5, verbose_name='Тип')),
                ('state', models.IntegerField(choices=[(1, 'Доставлено'), (-1, 'Отклонено'), (0, 'В ожидании'), (-2, 'Не отправлено (отправка запрещена настройками)')], default=0, verbose_name='Состояние')),
                ('event', models.IntegerField(blank=True, choices=[(1, 'Example')], null=True, verbose_name='Событие')),
                ('room_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название комнаты')),
                ('data_json', models.TextField(blank=True, null=True, verbose_name='Данные JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notifies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (получатель)')),
            ],
            options={
                'verbose_name': 'Ситемное уведомление',
                'verbose_name_plural': 'Системные уведомления',
            },
            bases=(models.Model, garpix_notify.mixins.notify_method_mixin.NotifyMethodsMixin),
        ),
        migrations.AddField(
            model_name='notifyuserlist',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to='garpix_notify.notifycategory', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SystemNotifyErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField(blank=True, default='', null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='garpix_notify.systemnotify', verbose_name='SystemNotify')),
            ],
            options={
                'verbose_name': 'Лог отправки системного уведомления',
                'verbose_name_plural': 'Логи отправки системных уведомлений',
            },
        ),
    ]
