# Generated by Django 3.2 on 2022-10-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0012_alter_systemnotify_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='is_delete_after',
            field=models.BooleanField(default=False, verbose_name='Удалять после отправки'),
        ),
        migrations.AddField(
            model_name='notifytemplate',
            name='is_delete_after',
            field=models.BooleanField(default=False, verbose_name='Удалять после отправки'),
        ),
    ]
