# Generated by Django 3.2 on 2023-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0013_auto_20221006_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotify',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
