# Generated by Django 3.2 on 2023-04-14 08:42

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_notify.utils.file
import garpix_notify.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0014_systemnotify_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytemplate',
            name='html_from_type',
            field=models.TextField(choices=[('ckeditor', 'Визуальный редактор'), ('zipfile', 'Загрузка из архива')], default='ckeditor', max_length=8, verbose_name='Способ формирования html'),
        ),
        migrations.AddField(
            model_name='notifytemplate',
            name='zipfile',
            field=models.FileField(blank=True, null=True, upload_to=garpix_notify.utils.file.get_file_path, validators=[garpix_notify.utils.validators.validate_zip], verbose_name='Файл архива'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='HTML'),
        ),
    ]
