# Generated by Django 3.2 on 2023-05-10 14:00

from django.db import migrations, models
import garpix_notify.utils.file
import garpix_notify.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0015_auto_20230414_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifytemplate',
            name='zipfile',
            field=models.FileField(blank=True, help_text='Поддерживаются архивы в форматах ZIP и RAR с единственным HTML-файлом и ассетами изображений по относительному или абсолютному пути', null=True, upload_to=garpix_notify.utils.file.get_file_path, validators=[garpix_notify.utils.validators.validate_zip], verbose_name='Файл архива'),
        ),
    ]
