# Generated by Django 3.2 on 2022-07-13 09:30

from django.db import migrations, models
import garpix_page.utils.all_sites


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_menu', '0003_auto_20220125_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sites',
            field=models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
