# Generated by Django 4.2 on 2024-03-14 11:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_keycloak_auth_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code sent date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email confirmation code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='New email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='New phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code sent date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone confirmation code'),
        ),
    ]
