# Generated by Django 3.1 on 2021-09-08 14:32

from django.db import migrations, models
import garpix_page.models.base_page


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='sites',
            field=models.ManyToManyField(default=garpix_page.models.base_page.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения'),
        ),
    ]
