# Generated by Django 3.1 on 2022-04-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('garpix_page', '0002_auto_20210908_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text_title', models.CharField(blank=True, default='', max_length=128, verbose_name='Заголовок')),
                ('text_title_ru', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ('created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, verbose_name='Порядок отображения')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basecomponent', verbose_name='Компонент')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.basepage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Компонент страницы',
                'verbose_name_plural': 'Компоненты страницы',
                'ordering': ('view_order',),
                'unique_together': {('component', 'page')},
            },
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='components', through='garpix_page.PageComponent', to='garpix_page.BasePage', verbose_name='Страницы для отображения'),
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_garpix_page.basecomponent_set+', to='contenttypes.contenttype'),
        ),
    ]
