# Generated by Django 3.2 on 2022-10-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_page', '0005_auto_20220713_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarpixPageSiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots_txt', models.TextField(default='User-agent: *\nDisallow: /admin/\nDisallow: /api/', verbose_name='Содержимое файла robots.txt')),
                ('sitemap_frequency', models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='always', max_length=7, verbose_name='Sitemap changefreq')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
