# Generated by Django 3.2 on 2023-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0007_grapesjshtmlcomponent_seotemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Полный URL страницы'),
        ),
    ]
