# Generated by Django 3.2 on 2022-11-07 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import garpix_user.mixins.models.confirm.code_length_mixin
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Referral way title')),
                ('referral_hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_password_confirm_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Restore password code')),
                ('is_restore_code_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Restore code confirmed')),
                ('restore_date', models.DateTimeField(null=True, verbose_name='Restore code sent date')),
                ('phone_confirmation_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone confirmation code')),
                ('phone_code_send_date', models.DateTimeField(blank=True, null=True, verbose_name='Code sent date')),
                ('new_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='New phone number')),
                ('email_confirmation_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email confirmation code')),
                ('email_code_send_date', models.DateTimeField(blank=True, null=True, verbose_name='Code sent date')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='New email')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Email confirmed')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone number')),
                ('is_phone_confirmed', models.BooleanField(default=False, verbose_name='Phone number confirmed')),
                ('token_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='user token')),
                ('recognized', models.PositiveIntegerField(choices=[(0, 'Undefined'), (1, 'Guest'), (2, 'Registered')], default=0, help_text='Indicates the state in which the user is recognized.', verbose_name='Type')),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last entrance')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'System user',
                'verbose_name_plural': 'System users',
            },
            bases=(garpix_user.mixins.models.confirm.code_length_mixin.CodeLengthMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
            },
        ),
        migrations.CreateModel(
            name='ReferralUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_user.referraltype', verbose_name='Where did the user come from')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_user.usersession', verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'referral_type')},
            },
        ),
    ]
