# Generated by Django 3.2 on 2023-03-07 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0002_auto_20221107_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'Системный пользователь', 'verbose_name_plural': 'Системные пользователи'},
        ),
        migrations.AddField(
            model_name='usersession',
            name='restore_by',
            field=models.CharField(choices=[('phone', 'Номер телефона'), ('email', 'Адрес электронной почты')], default='email', max_length=5),
        ),
        migrations.AlterField(
            model_name='referraltype',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название реферрального пути'),
        ),
        migrations.AlterField(
            model_name='referraluserlink',
            name='referral_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_user.referraltype', verbose_name='Откуда пришел пользователь'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='email_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления кода'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения email'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='Номер телефона подтвержден'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_restore_code_confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Код восстановления подтвержден'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний вход'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Новый email'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Новый номер телефона'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='phone_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления кода'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='phone_confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код подтверждения номера телефона'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='recognized',
            field=models.PositiveIntegerField(choices=[(0, 'Не найден'), (1, 'Гость'), (2, 'Зарегистрирован')], default=0, help_text='Обозначает состояние, в котором распознается пользователь.', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='restore_date',
            field=models.DateTimeField(null=True, verbose_name='Дата отправки кода восстановления'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='restore_password_confirm_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код восстановления пароля'),
        ),
    ]
