# Generated by Django 3.2 on 2023-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0006_garpixuserpasswordconfiguration_password_validity_inform_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='garpixuserpasswordconfiguration',
            name='access_token_ttl_seconds',
            field=models.IntegerField(default=0, help_text='0 если ограничение не требуется', verbose_name='Время жизни авторизационного токена'),
        ),
        migrations.AddField(
            model_name='garpixuserpasswordconfiguration',
            name='refresh_token_ttl_seconds',
            field=models.IntegerField(default=0, help_text='0 если ограничение не требуется', verbose_name='Время жизни рефреш токена'),
        ),
    ]
