# Generated by Django 3.2 on 2024-01-18 10:38

from django.db import migrations, models
import garpix_user.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_user', '0007_auto_20231127_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='garpixuserpasswordconfiguration',
            name='access_tokens_count',
            field=models.IntegerField(default=-1, help_text='-1 если отправка уведомлений не требуется', validators=[garpix_user.utils.validators.PositiveWithInfValidator(limit_value=[])], verbose_name='Количество хранимых access-токенов (самый старый будет удален)'),
        ),
    ]
