# Generated by Django 4.2 on 2024-03-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_user', '0008_garpixuserpasswordconfiguration_access_tokens_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'verbose_name': 'Password history', 'verbose_name_plural': 'Password history'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'System user', 'verbose_name_plural': 'System users'},
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='referraltype',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Referral way title'),
        ),
        migrations.AlterField(
            model_name='referraluserlink',
            name='referral_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_user.referraltype', verbose_name='Where did the user come from'),
        ),
        migrations.AlterField(
            model_name='referraluserlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_user.usersession', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='email_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code sent date'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email confirmation code'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='Phone number confirmed'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last entrance'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='New email'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='New phone number'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='phone_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code sent date'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='phone_confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone confirmation code'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='recognized',
            field=models.PositiveIntegerField(choices=[(0, 'Undefined'), (1, 'Guest'), (2, 'Registered')], default=0, help_text='Indicates the state in which the user is recognized.', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
