name: Publish to PyPI and TestPyPI

on:
  release:
    types: [published]

env:
  PYPI_URL: https://pypi.org/p/garpixcms
  PYPI_TEST_URL: https://test.pypi.org/p/garpixcms
  UPLOAD_DIR: backend/dist/
  DOWNLOAD_DIR: dist/


jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run:
        python3 -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: ${{ env.UPLOAD_DIR }}

  publish-to-pypi:
    name: >-
      Publish to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: ${{ env.PYPI_URL }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: ${{ env.DOWNLOAD_DIR }}
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.10

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: ${{ env.PYPI_TEST_URL }}

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: ${{ env.DOWNLOAD_DIR }}
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1.10
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
